package dev.toqash.travelplannerbackend.config;

public enum ErrorCode {
    EMAIL_TAKEN,
    INVALID_CREDENTIALS,
    VALIDATION_FAILED,
    INTERNAL_ERROR,
    TRIP_NOT_FOUND,
    VERSION_CONFLICT,
    ITINERARY_NOT_FOUND,
    AI_UNAVAILABLE,
    AI_OUTPUT_INVALID,
    GENERATION_IN_PROGRESS,
    JOB_NOT_FOUND,
    INTERRUPTED
}