-- One itinerary per trip; generated by the AI or built by hand.
CREATE TABLE itineraries (
     id         UUID        NOT NULL,
     trip_id    UUID        NOT NULL,
     summary    TEXT,
     status     VARCHAR(20) NOT NULL DEFAULT 'CURRENT',
     version    BIGINT      NOT NULL DEFAULT 0,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

     CONSTRAINT itineraries_pkey PRIMARY KEY (id),
     CONSTRAINT fk_itineraries_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    -- Also serves as the index for lookups by trip.
     CONSTRAINT uq_itineraries_trip UNIQUE (trip_id),
    -- OUT_OF_SYNC: the trip's dates changed after the itinerary was created.
     CONSTRAINT ck_itineraries_status CHECK (status IN ('CURRENT', 'OUT_OF_SYNC'))
);

CREATE TABLE itinerary_days (
    id           UUID         NOT NULL,
    itinerary_id UUID         NOT NULL,
    day_number   INT          NOT NULL,
    date         DATE         NOT NULL,
    theme        VARCHAR(200),
    notes        TEXT,

    CONSTRAINT itinerary_days_pkey PRIMARY KEY (id),
    CONSTRAINT fk_itinerary_days_itinerary FOREIGN KEY (itinerary_id) REFERENCES itineraries (id) ON DELETE CASCADE,
    CONSTRAINT ck_itinerary_days_day_number CHECK (day_number >= 1),

    CONSTRAINT uq_itinerary_days_number UNIQUE (itinerary_id, day_number),
    CONSTRAINT uq_itinerary_days_date UNIQUE (itinerary_id, date)
);

CREATE TABLE activities (
    id          UUID         NOT NULL,
    day_id      UUID         NOT NULL,
    position    INT          NOT NULL,
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    category    VARCHAR(20)  NOT NULL,
    cost_level  VARCHAR(20)  NOT NULL,
    start_time  TIME         NOT NULL,
    end_time    TIME         NOT NULL,
    place_name  VARCHAR(200),
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    locked      BOOLEAN      NOT NULL DEFAULT FALSE,
    source      VARCHAR(10)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT activities_pkey PRIMARY KEY (id),
    CONSTRAINT fk_activities_day FOREIGN KEY (day_id) REFERENCES itinerary_days (id) ON DELETE CASCADE,
    CONSTRAINT ck_activities_position CHECK (position >= 0),
    CONSTRAINT ck_activities_times CHECK (start_time < end_time),
    CONSTRAINT ck_activities_category CHECK (category IN
        ('SIGHTSEEING', 'FOOD', 'CULTURE', 'NATURE', 'SHOPPING', 'NIGHTLIFE', 'ACTIVITY', 'TRANSPORT', 'REST')),
    CONSTRAINT ck_activities_cost_level CHECK (cost_level IN ('FREE', 'LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_activities_source CHECK (source IN ('AI', 'USER')),
    -- Coordinates are optional, but always come as a valid pair.
    CONSTRAINT ck_activities_coordinates CHECK (
        (latitude IS NULL AND longitude IS NULL)
            OR (latitude IS NOT NULL AND longitude IS NOT NULL
            AND latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)),
    -- The leading day_id column also indexes the foreign key.
    CONSTRAINT uq_activities_day_position UNIQUE (day_id, position) DEFERRABLE INITIALLY DEFERRED
);